### ISSUE TITLE
Running the go application

### ISSUE THREAD

**Issue by htcosta** [saschagrunert/fosdem20#1]
Go is not really my thing, i assume that i am missing some kind of go package.

**Issue:**
./main.go: line 1: package: command not found
./main.go: line 3: syntax error near unexpected token `newline'
./main.go: line 3: `import ('

go version go1.14.6 linux/amd64

**Comment by saschagrunert** [comment]
Hey, thanks for opening the issue. Which command do you execute to get the error? :)

**Comment by htcosta** [comment]
I have executed the main.go file ( ./main.go), just saw that the go application is not compiled.

This is not a bug, its just the lack of go knowledge.

Maybe a install/run set of instructions in de readme file, for people that don't know go ?

**Comment by saschagrunert** [comment]
Yeah you have to install the go programming language (see https://golang.org/doc/install) and then run `go run ./main.go`. :)

**Comment by htcosta** [comment]
Its working, thanks Sasha

As for reference for people with no go knowledge, run **go run ./main.go --help**  :)
